trigger:
- master

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'

name: $(Build.Reason)_commit-$(Build.SourceVersion)_$(Date:yyyyMMdd_HHmmss)

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: NuGetToolInstaller@1
  
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - task: PowerShell@2
    displayName: Update Project File
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)\Build\UpdateProjectFile.ps1'
      arguments: '-PathToCsprojFile $(SYSTEM.DefaultWorkingDirectory)\BricklinkSharp.Client\BricklinkSharp.Client.csproj -BuildId $(Build.BuildId)'

  - task: VSBuild@1
    displayName: Build Solution
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Run Unit Tests
    inputs:
      command: 'test'
      projects: '**/*.Tests.csproj'
      arguments: '-c $(buildConfiguration)'
      
  - task: CopyFiles@2
    inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: BricklinkSharp.Client\bin\$(BuildConfiguration)\**
        TargetFolder: '$(Build.ArtifactsStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
        PathtoPublish: '$(Build.ArtifactsStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'